### ISSUE TITLE
Not building for CircleCI

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-permute-feedstock#3]
The latest PR from @rvalieris (#1) was not built for CircleCI.

@isuruf Is this related to your closed Issue #2 to update the CircleCI deploy key?

Also potentially related, my PR to r-automap (https://github.com/conda-forge/r-automap-feedstock/pull/1) failed to build for CircleCI last week, but this morning suddenly worked without me changing anything. Thus maybe we just need to re-trigger the CircleCI build somehow. I'm not a maintainer on this feedstock, so I am limited in my ability to fix this.

cc @bgruening

**Comment by ocefpaf** [comment]
I just pushed an empty commit to start a new build. We did need the new token that @isuruf add in #2 though for that to work.

See https://circleci.com/gh/conda-forge/r-permute-feedstock

**Comment by jdblischak** [comment]
@ocefpaf Great. Thanks!

**Comment by ocefpaf** [comment]
No problem. BTW, I was travelling this past weeks, so I might have missed a few "pings," if you still need me somewhere else please feel free to just ping me again.

**Comment by jdblischak** [comment]
@ocefpaf Will do! As always, thanks so much for all you do!
